version: '3'

tasks:
  default:
    cmds:
      - task: run:benchmark

  install:task:
    desc: Installs go-task (task runner)
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest

  build:cpp:
    cmds:
      - cmd: cmake -S . -B build -DSHM_BUILD_BENCHMARKS=ON -DCMAKE_BUILD_TYPE=Release
      - cmd: cmake --build build --config Release --parallel

  build:go:
    dir: benchmarks/go
    cmds:
      - go build -o {{if eq OS "windows"}}server.exe{{else}}server{{end}} main.go

  build:
    deps: [build:cpp, build:go]

  run:benchmark:
    desc: Runs Direct benchmark
    deps: [build]
    cmds:
      - task: run:case
        vars: { THREADS: 1 }
      - task: run:case
        vars: { THREADS: 4 }
      - task: run:case
        vars: { THREADS: 8 }

  run:case:
    internal: true
    cmds:
      # Cleanup before run
      - task: kill_server
      - cmd: rm -f /dev/shm/SimpleIPC* || true
        ignore_error: true
        platforms: [linux]

      # Start Server
      - cmd: './benchmarks/go/server -w {{.THREADS}} > server_{{.THREADS}}.log 2>&1 &'
        platforms: [linux]
      - cmd: 'cmd /c "start /B benchmarks\go\server.exe -w {{.THREADS}} > server_{{.THREADS}}.log 2>&1"'
        platforms: [windows]

      # Wait for start
      - cmd: sleep 1
        platforms: [linux]
      - cmd: 'timeout /t 1 /nobreak > nul'
        platforms: [windows]

      # Run Client
      - cmd: './build/benchmarks/shm_benchmark -t {{.THREADS}}'
        platforms: [linux]
      - cmd: 'build\benchmarks\shm_benchmark.exe -t {{.THREADS}}'
        platforms: [windows]

      # Cleanup
      - defer: { task: kill_server }

  kill_server:
    cmds:
      - cmd: pkill -f "server -w" || true
        platforms: [linux]
      - cmd: taskkill /F /IM server.exe || true
        platforms: [windows]

  xll:default:
    desc: "Builds all components for the XLL experiment."
    cmds:
      - task -f ./experiments/xll/Taskfile.yml default
