version: '3'

tasks:
  default:
    cmds:
      - task: run:benchmark

  build:cpp:
    dir: benchmarks/build
    cmds:
      - cmd: cmake .. -DCMAKE_BUILD_TYPE=Release
      - cmd: '{{if eq OS "windows"}}cmake --build . --config Release{{else}}make -j$(nproc){{end}}'

  build:go:
    dir: benchmarks/go
    cmds:
      - go build -o {{if eq OS "windows"}}server.exe{{else}}server{{end}} main.go

  build:
    deps: [build:cpp, build:go]

  run:benchmark:
    desc: Runs SPSC benchmark
    deps: [build]
    cmds:
      - task: run:case
        vars: { THREADS: 1, MODE: spsc }
      - task: run:case
        vars: { THREADS: 4, MODE: spsc }
      - task: run:case
        vars: { THREADS: 8, MODE: spsc }

  run:benchmark_direct:
    desc: Runs Direct benchmark
    deps: [build]
    cmds:
      - task: run:case
        vars: { THREADS: 1, MODE: direct }
      - task: run:case
        vars: { THREADS: 4, MODE: direct }
      - task: run:case
        vars: { THREADS: 8, MODE: direct }

  run:case:
    internal: true
    cmds:
      # Cleanup before run
      - task: kill_server
      - cmd: rm -f server_*.log || true
        ignore_error: true
      - cmd: rm -f /dev/shm/SimpleIPC* || true
        ignore_error: true
        platforms: [linux]

      # Start Server (pass mode)
      - cmd: './benchmarks/go/server -w {{.THREADS}} -mode {{.MODE}} > server_{{.MODE}}_{{.THREADS}}.log 2>&1 &'
        platforms: [linux]
      - cmd: 'cmd /c "start /B benchmarks\\go\\server.exe -w {{.THREADS}} -mode {{.MODE}} > server_{{.MODE}}_{{.THREADS}}.log 2>&1"'
        platforms: [windows]

      # Wait for start
      - cmd: sleep 1
        platforms: [linux]
      - cmd: 'timeout /t 1 /nobreak > nul'
        platforms: [windows]

      # Run Client
      - cmd: './benchmarks/build/shm_benchmark -t {{.THREADS}} -mode {{.MODE}} > cpp_client_{{.MODE}}_{{.THREADS}}.log 2>&1'
        platforms: [linux]
      - cmd: 'benchmarks\\build\\shm_benchmark.exe -t {{.THREADS}} -mode {{.MODE}} > cpp_client_{{.MODE}}_{{.THREADS}}.log 2>&1'
        platforms: [windows]

      # Cleanup
      - defer: { task: kill_server }

  kill_server:
    cmds:
      - cmd: pkill -f "server -w" || true
        platforms: [linux]
      - cmd: taskkill /F /IM server.exe || true
        platforms: [windows]
