#pragma once
#include <cstdint>

namespace shm {

/**
 * @brief Transport Header structure for IPC messages.
 *
 * This header is prepended to the user payload when using the high-level
 * IPCHost and IPCGuest facade. It allows for asynchronous request-response
 * matching via a request ID.
 *
 * @note The memory layout is packed to ensure consistent 8-byte alignment
 * across C++ and Go.
 */
#pragma pack(push, 1)
struct TransportHeader {
    /**
     * @brief Unique Request ID.
     *
     * Generated by the Host for each request. The Guest must echo this ID
     * back in the response header to allow the Host to resolve the pending promise.
     */
    uint64_t req_id;
};
#pragma pack(pop)

}
